trigger:
  branches:
    include:
    - master
    - validate/*
    - release/*
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: f62fe945-b078-4791-94ac-685c94dad016
  ci_feed: /e08c98c0-63d6-4dc6-80ca-944e4deaf3d2
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
